version: '3.7'

# 컴퓨터들
services:

  # 컴퓨터이름
  my-backend:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./index.js:/myfolder/index.js
      - ./src:/myfolder/src
      - ./models:/myfolder/models
      - ./swagger:/myfolder/swagger
    ports:
      - 3000:3000

  #컴퓨터이름
  my-database:
    image: mongo:5
    ports:
      - 27017:27017
